### ISSUE TITLE
Add f7 font size

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/vtex-tachyons#5]
Mapeando para 12px. Já estou usando uma versão customizada aqui:

![image](https://cloud.githubusercontent.com/assets/3229933/20764395/24ba4068-b715-11e6-8fef-827cd4e27ec3.png)

**Comment by dfosco** [comment]
Proposto: 

```css
.f1 { font-size: 3rem; } // mais 0.75
.f2 { font-size: 2.25rem; } // mais 0.75
.f3 { font-size: 1.5rem; } // mais .25
.f4 { font-size: 1.25rem; } // mais .25
.f5 { font-size: 1rem; } // neutra
.f6 { font-size: .875rem; } // menos .125
.f7 { font-size: .810rem; } // menos .125
```
